### ISSUE TITLE
Problem after update ngrx/store to version 11

### ISSUE THREAD

**Issue by daveksb** [timdeschryver/ngrx-immer#3] opened 2021-02-10 03:51 UTC
![issue](https://user-images.githubusercontent.com/15795314/107461911-8ae8b780-6b8d-11eb-8dfe-6b713a92bcd6.jpg)
While above code work correctly with ngrx version 10
After update ngrx/store to version 11 immerOn() doesn't know the type of state.
In this case it return state as unknow type.

**Comment by timdeschryver** [comment] 2021-02-10 09:01
Hi thanks for reporting this @daveksb , this should be resolved in v0.0.05

**Closed as completed** 2021-02-21 17:05 UTC

**Comment by azran4u** [comment] 2021-06-13 08:51
Hi, just installed version 0.0.5 and the issue is still happaning
![immer js type error](https://user-images.githubusercontent.com/24504795/121801011-b49a1400-cc3d-11eb-9533-bb96ee82afe2.png)

**Comment by timdeschryver** [comment] 2021-06-13 09:11
@azran4u can you share your ngrx and typescript versions please.

**Comment by azran4u** [comment] 2021-06-13 09:18
ngrx 10.1.2
typescript 4.3.2

**Comment by timdeschryver** [comment] 2021-06-13 09:28
@azran4u it would be great if you could create a reproduction

**Comment by evanrooijen** [comment] 2021-11-09 09:41
Please re-open as this issue still occurs.

ngrx/store 10.0.0
typescript 4.0.3

**Comment by timdeschryver** [comment] 2021-11-09 17:46
@evanrooijen can you share a reproduction please.
